package germplasm.database.api.dto;

import germplasm.database.api.model.Germplasm;

public record DataDetailingGermplasmDTO(

        Integer id,
        String nome,
        String tipoDeMaterialGenetico,
        String texturaDoGrao,
        String origem,
        Boolean transgenico,
        String eventosTransgenicos,
        String localNaCamaraFria,
        String dataDeEntrada,
        String dataDaUltimaColheita,
        Float colletotrichumGraminicola,
        Float pucciniaSorghi,
        Float exserohilumTurcicum,
        Float phaeosphaeriaMaydis,
        Float pucciniaPolysora,
        Float physopellaZeae,
        Float cornStunt,
        Float diplodiaMaydis,
        Float fusariumMoniliforme,
        Float gibberellaZeae,
        Float alturaDePlanta,
        Float alturaDeEspiga,
        Float diametroDaEspiga,
        Float numeroDeGraosPorFileira,
        Float numeroDeFileirasDeGraosPorEspiga,
        Float comprimentoDeEspigas,
        Float rendimentoDeGraos,
        Float capacidadeDeExpansao,
        Float massaDeCemGraos,
        Float numeroDeEspigas,
        Float diametroDoColmo,
        Float comprimentoDeGrao,
        Float larguraDeGrao,
        Float espessuraDeGrao,
        Float espessuraDoPericarpo,
        Float difusividadeTermicaDoPericarpo,
        Float teorDeProteina,
        Float teorDeOleo,
        Float amidoTotal,
        Integer primeiraFolhaPigmentacaoAntocianinicaDaBainha,
        Integer primeiraFolhaFormaDoApice,
        Integer folhagemIntensidadeDaCorVerde,
        Integer folhaOndulacaoDaMargemDaLamina,
        Integer folhaAnguloEntreALaminaEOColmo,
        Integer folhaCurvaturaDaLamina,
        Integer colmoGrauDoZigZag,
        Integer pendaoCicloAteAAntese,
        Integer pendaoPigmentacaoAntocianinicaNaBaseDaGluma,
        Integer pendaoPigmentacaoAntocianinicaDaGlumaExcluidaABase,
        Integer pendaoPigmentacaoAntocianinicaDasAnteras,
        Integer pendaoAnguloEntreOEixoPrincipalEOsRamosLaterais,
        Integer pendaoCurvaturaDosRamosLaterais,
        Integer pendaoNumeroDeRamificacoesPrimarias,
        Integer espigaCicloAteOAparecimentoDosEstigmas,
        Integer espigaPigmentacaoAntocianinicaDosEstigmas,
        Integer colmoPigmentacaoAntocianinicaDasRaizesAereas,
        Integer pendaoDensidadeDasEspiguetas,
        Integer folhaPigmentacaoAntocianinicaDaBainha,
        Integer colmoPigmentacaoAntocianinicaDosEntrenos,
        Integer pendaoCompDoEixoPrincipalAcimaDoRamoLateralMaisBaixo,
        Integer pendaoCompDoEixoPrincipalAcimaDoRamoLateralMaisAlto,
        Integer pendaoCompDoRamoLateral,
        Integer plantaComp,
        Integer plantaRelacaoAltInsPedunculoEspigaMaisAltaECompPlanta,
        Integer folhaLarguraDaLamina,
        Integer pedunculoComp,
        Integer espigaComp,
        Integer espigaDiametroNoMeioDaEspiga,
        Integer espigaForma,
        Integer espigaNumeroDeFileirasDeGraos,
        Integer espigaNumeroDeCoresDosGraos,
        Integer graoIntensidadeDaCorAmarela,
        Integer graoComp,
        Integer graoLargura,
        Integer espigaTipoDeGrao,
        Integer espigaEnrugamentoDoExtremoSuperiorDoGrao,
        Integer espigaCorDoExtremoSuperiorDoGrao,
        Integer espigaCorDoLadoDorsalDoGrao,
        Integer tipoDeGraoEstourado,
        Integer espigaPigmentacaoAntocianinicaDasGlumasDoSabugo,
        String informacoesAdicionais
) {

    public DataDetailingGermplasmDTO(Germplasm germplasm) {
        this(
                germplasm.getId(),
                germplasm.getNome(),
                germplasm.getTipoDeMaterialGenetico(),
                germplasm.getTexturaDoGrao(),
                germplasm.getOrigem(),
                germplasm.getTransgenico(),
                germplasm.getEventosTransgenicos(),
                germplasm.getLocalNaCamaraFria(),
                germplasm.getDataDeEntrada(),
                germplasm.getDataDaUltimaColheita(),
                germplasm.getColletotrichumGraminicola(),
                germplasm.getPucciniaSorghi(),
                germplasm.getExserohilumTurcicum(),
                germplasm.getPhaeosphaeriaMaydis(),
                germplasm.getPucciniaPolysora(),
                germplasm.getPhysopellaZeae(),
                germplasm.getCornStunt(),
                germplasm.getDiplodiaMaydis(),
                germplasm.getFusariumMoniliforme(),
                germplasm.getGibberellaZeae(),
                germplasm.getAlturaDePlanta(),
                germplasm.getAlturaDeEspiga(),
                germplasm.getDiametroDaEspiga(),
                germplasm.getNumeroDeGraosPorFileira(),
                germplasm.getNumeroDeFileirasDeGraosPorEspiga(),
                germplasm.getComprimentoDeEspigas(),
                germplasm.getRendimentoDeGraos(),
                germplasm.getCapacidadeDeExpansao(),
                germplasm.getMassaDeCemGraos(),
                germplasm.getNumeroDeEspigas(),
                germplasm.getDiametroDoColmo(),
                germplasm.getComprimentoDeGrao(),
                germplasm.getLarguraDeGrao(),
                germplasm.getEspessuraDeGrao(),
                germplasm.getEspessuraDoPericarpo(),
                germplasm.getDifusividadeTermicaDoPericarpo(),
                germplasm.getTeorDeProteina(),
                germplasm.getTeorDeOleo(),
                germplasm.getAmidoTotal(),
                germplasm.getPrimeiraFolhaPigmentacaoAntocianinicaDaBainha(),
                germplasm.getPrimeiraFolhaFormaDoApice(),
                germplasm.getFolhagemIntensidadeDaCorVerde(),
                germplasm.getFolhaOndulacaoDaMargemDaLamina(),
                germplasm.getFolhaAnguloEntreALaminaEOColmo(),
                germplasm.getFolhaCurvaturaDaLamina(),
                germplasm.getColmoGrauDoZigZag(),
                germplasm.getPendaoCicloAteAAntese(),
                germplasm.getPendaoPigmentacaoAntocianinicaNaBaseDaGluma(),
                germplasm.getPendaoPigmentacaoAntocianinicaDaGlumaExcluidaABase(),
                germplasm.getPendaoPigmentacaoAntocianinicaDasAnteras(),
                germplasm.getPendaoAnguloEntreOEixoPrincipalEOsRamosLaterais(),
                germplasm.getPendaoCurvaturaDosRamosLaterais(),
                germplasm.getPendaoNumeroDeRamificacoesPrimarias(),
                germplasm.getEspigaCicloAteOAparecimentoDosEstigmas(),
                germplasm.getEspigaPigmentacaoAntocianinicaDosEstigmas(),
                germplasm.getColmoPigmentacaoAntocianinicaDasRaizesAereas(),
                germplasm.getPendaoDensidadeDasEspiguetas(),
                germplasm.getFolhaPigmentacaoAntocianinicaDaBainha(),
                germplasm.getColmoPigmentacaoAntocianinicaDosEntrenos(),
                germplasm.getPendaoCompDoEixoPrincipalAcimaDoRamoLateralMaisBaixo(),
                germplasm.getPendaoCompDoEixoPrincipalAcimaDoRamoLateralMaisAlto(),
                germplasm.getPendaoCompDoRamoLateral(),
                germplasm.getPlantaComp(),
                germplasm.getPlantaRelacaoAltInsPedunculoEspigaMaisAltaECompPlanta(),
                germplasm.getFolhaLarguraDaLamina(),
                germplasm.getPedunculoComp(),
                germplasm.getEspigaComp(),
                germplasm.getEspigaDiametroNoMeioDaEspiga(),
                germplasm.getEspigaForma(),
                germplasm.getEspigaNumeroDeFileirasDeGraos(),
                germplasm.getEspigaNumeroDeCoresDosGraos(),
                germplasm.getGraoIntensidadeDaCorAmarela(),
                germplasm.getGraoComp(),
                germplasm.getGraoLargura(),
                germplasm.getEspigaTipoDeGrao(),
                germplasm.getEspigaEnrugamentoDoExtremoSuperiorDoGrao(),
                germplasm.getEspigaCorDoExtremoSuperiorDoGrao(),
                germplasm.getEspigaCorDoLadoDorsalDoGrao(),
                germplasm.getTipoDeGraoEstourado(),
                germplasm.getEspigaPigmentacaoAntocianinicaDasGlumasDoSabugo(),
                germplasm.getInformacoesAdicionais()
        );
    }


}

